schema_version: 1.0
columns:
  claim_id:
    type: integer
    nullable: false
  policy_id:
    type: integer
    nullable: false
  claim_date:
    type: datetime
    nullable: false
  claim_amount:
    type: float
    nullable: false
    constraints:
      min: 100.0
      max: 100000.0
  claim_type:
    type: string
    nullable: true
