schema_version: 1.0
columns:
  timestamp:
    type: datetime
    nullable: false
  symbol:
    type: string
    nullable: false
  price:
    type: float
    nullable: false
    constraints:
      min: 0.0
      max: 100000.0
  volume:
    type: integer
    nullable: false
    constraints:
      min: 0

