schema_version: 1.0
columns:
  student_id:
    type: integer
    nullable: false
  assessment_id:
    type: integer
    nullable: false
  subject:
    type: string
    nullable: false
  score:
    type: float
    nullable: false
    constraints:
      min: 0.0
      max: 100.0
  assessment_date:
    type: datetime
    nullable: false
